const level1 = new Level(
    [   
        //Background Hell
        new BackgroundObject('./img/Background/Pale/bg.png', 0, 480),
        new BackgroundObject('./img/Background/Pale/myst.png', 0, 480),
        new BackgroundObject('./img/Background/Pale/rock1.png', 0, 480),
        new BackgroundObject('./img/Background/Pale/rock2.png', 0, 480),
        new BackgroundObject('./img/Background/Pale/rock3.png', 0, 480),
        new BackgroundObject('./img/Background/Pale/rock5.png', 0, 480),

        new BackgroundObject('./img/Background/Pale/bg.png', 719, 480),
        new BackgroundObject('./img/Background/Pale/myst.png', 719, 480),
        new BackgroundObject('./img/Background/Pale/rock1.png', 719, 480),
        new BackgroundObject('./img/Background/Pale/rock2.png', 719, 480),
        new BackgroundObject('./img/Background/Pale/rock3.png', 719, 480),
        new BackgroundObject('./img/Background/Pale/rock5.png', 719, 480),

        new BackgroundObject('./img/Background/Pale/bg.png', 719*2, 480),
        new BackgroundObject('./img/Background/Pale/myst.png', 719*2, 480),
        new BackgroundObject('./img/Background/Pale/rock1.png', 719*2, 480),
        new BackgroundObject('./img/Background/Pale/rock2.png', 719*2, 480),
        new BackgroundObject('./img/Background/Pale/rock3.png', 719*2, 480),
        new BackgroundObject('./img/Background/Pale/rock5.png', 719*2, 480),

        new BackgroundObject('./img/Background/Pale/bg.png', 719*3, 480),
        new BackgroundObject('./img/Background/Pale/myst.png', 719*3, 480),
        new BackgroundObject('./img/Background/Pale/rock1.png', 719*3, 480),
        new BackgroundObject('./img/Background/Pale/rock2.png', 719*3, 480),
        new BackgroundObject('./img/Background/Pale/rock3.png', 719*3, 480),
        new BackgroundObject('./img/Background/Pale/rock5.png', 719*3, 480),
    ],
    [   
        //Background Mountain
        new BackgroundObject('./img/Background/Bright/sky.png', 0, 0),
        new BackgroundObject('./img/Background/Bright/clouds_back_layer2.png', 0, 0),
        new BackgroundObject('./img/Background/Bright/clouds_back_layer1.png', 0, 0),
        new BackgroundObject('./img/Background/Bright/coluds_small.png', 0, 0),
        new BackgroundObject('./img/Background/Bright/mountains.png', 0, 0),
        new BackgroundObject('./img/Background/Bright/trees.png', 0, 0),

        new BackgroundObject('./img/Background/Bright/sky.png', 719, 0),
        new BackgroundObject('./img/Background/Bright/clouds_back_layer2.png', 719, 0),
        new BackgroundObject('./img/Background/Bright/clouds_back_layer1.png', 719, 0),
        new BackgroundObject('./img/Background/Bright/coluds_small.png', 719, 0),
        new BackgroundObject('./img/Background/Bright/mountains.png', 719, 0),
        new BackgroundObject('./img/Background/Bright/trees.png', 719, 0),

        new BackgroundObject('./img/Background/Bright/sky.png', 719*2, 0),
        new BackgroundObject('./img/Background/Bright/clouds_back_layer2.png', 719*2, 0),
        new BackgroundObject('./img/Background/Bright/clouds_back_layer1.png', 719*2, 0),
        new BackgroundObject('./img/Background/Bright/coluds_small.png', 719*2, 0),
        new BackgroundObject('./img/Background/Bright/mountains.png', 719*2, 0),
        new BackgroundObject('./img/Background/Bright/trees.png', 719*2, 0),

        new BackgroundObject('./img/Background/Bright/sky.png', 719*3, 0),
        new BackgroundObject('./img/Background/Bright/clouds_back_layer2.png', 719*3, 0),
        new BackgroundObject('./img/Background/Bright/clouds_back_layer1.png', 719*3, 0),
        new BackgroundObject('./img/Background/Bright/coluds_small.png', 719*3, 0),
        new BackgroundObject('./img/Background/Bright/mountains.png', 719*3, 0),
        new BackgroundObject('./img/Background/Bright/trees.png', 719*3, 0),
    ],
    [   
        //ground_hell
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 0, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 50, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 100, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 150, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 200, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 250, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 300, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 350, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 400, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 450, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 500, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 550, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 600, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 650, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 700, 430),
        
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 750, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 800, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 850, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 900, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 950, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1000, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1050, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1100, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1150, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1200, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1250, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1300, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1350, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1400, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1450, 430),
        
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1500, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1550, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1600, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1650, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1700, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1750, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1800, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1850, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1900, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 1950, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 2000, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 2050, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 2100, 430),
        new TileObject('./img/Background/Tiles/Tiles_rock/tile2.png', 2150, 430),
        
        new TileObject('./img/Background/Tiles/Tiles_lava/lava_tile3.png', 2200, 430),
        new TileObject('./img/Background/Tiles/Tiles_lava/lava_tile3.png', 2250, 430),
        new TileObject('./img/Background/Tiles/Tiles_lava/lava_tile3.png', 2300, 430),
        new TileObject('./img/Background/Tiles/Tiles_lava/lava_tile3.png', 2350, 430),
        new TileObject('./img/Background/Tiles/Tiles_lava/lava_tile3.png', 2400, 430),
    ],
    [   
        //ground_grass
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 0, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 50, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 100, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 150, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 200, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 250, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 300, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 350, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 400, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 450, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 500, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 550, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 600, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 650, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 700, 430),

        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 750, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 800, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 850, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 900, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 950, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1000, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1050, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1100, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1150, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1200, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1250, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1300, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1350, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1400, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1450, 430),

        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1500, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1550, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1600, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1650, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1700, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1750, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1800, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1850, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1900, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 1950, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 2000, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 2050, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 2100, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 2150, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 2200, 430),

        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 2250, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 2300, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 2350, 430),
        new TileObject('./img/Background/Tiles/Ground_grass_0001_tile.png', 2400, 430),
    ],
    [
        new Bird(),
        new Bird(),
        new Bird(),
        new Bird(),
        new Bird(),
    ],
    [
        new EnemyOne(),
        new EnemyTwo(),
        new EnemyTwo(),
        new EnemyTwo(),
        new EnemyTwo(),
        new EnemyTwo(),
        new EnemyTwo(),
        new EnemyOne(),
        new EnemyTwo(),
        // new EnemyBoss(),
    ],
    [],
);